### ISSUE TITLE
Erstellen von TarmedExtension auf leerer DB nicht möglich

### ISSUE THREAD

**Issue by col-panic** [elexis/elexis-3-base#111]
Lt. Elexis-Os Mailingliste https://sourceforge.net/p/elexis/mailman/message/36160937/ funktioniert der Tarmed Import bei leerer DB nicht.

Es ist auch ein Patch beigelegt.

**Comment by huthomas** [comment]
Wurde im master und 3.4 gefixed. Danke fürs testen und melden.
