### ISSUE TITLE
MediPort plugin läuft nicht mehr unter Elexis 3.4

### ISSUE THREAD

**Issue by ngiger** [elexis/elexis-3-base#119]
Cathrine Manesse reported

<pre>
Wir haben im neuen Jahr auf Elexis 3.1 gewechselt, damit auch die neuen 
Tarmed Positionen eingezogen. Das ging alles gut. Nun habe ich aber von 
den KK folgende Mitteilung nach Versand meiner Rechnungen via medidata 
erhalten:

Beim guarantor fehlt der Namespace «invoice:»
In Ihrem XML:
</invoice:patient>
<guarantorxmlns="http://www.forum-datenaustausch.ch/invoice">
<invoice:person>
Richtig wäre:
</invoice:patient>
<invoice:guarantorxmlns="http://www.forum-datenaustausch.ch/invoice">
<invoice:person>
Bei den alten XML files ist invoice:quarantor noch drin.....
</pre>

Ich werde mich um das Problem kümmern.

**Comment by rgwch** [comment]
Bei Franz Brändli machte Mediport auch Probleme. Beim Versuch, die Einstellungsseite zu öffnen, warf das Plugin einen ArrayIndexOutOfBounds-Exception
Hier https://github.com/elexis/elexis-3-base/blob/master/ch.medshare.mediport/src/ch/medshare/mediport/config/Client.java in zeile 47.

Da ich mich mit Mediport nicht auskenne, und auch nichts damit zu tun haben will, habe ich das Konfigurationsfile einfach so angepasst, dass die beiden betreffenden Zeilen der Erwartung entsprechen.

Aber wenn Du eh schon am Ändern bist, könntest du ja auch einen Test auf die Arraylänge von parts[] einbauen, befor auf parts[3] zugegriffen wird.

**Comment by col-panic** [comment]
Timeout
