### ISSUE TITLE
TarmedOptifier: Limite für 00.0050/00.0055 (Vorbesprechung) angezeigt, aber trotzdem addiert

### ISSUE THREAD

**Issue by marlovitsh** [elexis/elexis-3-base#132]
00.0050 -> Meldung, dass nur 6 * - wird aber trotzdem weiter addiert
00.0055 -> idem

**Comment by col-panic** [comment]
Danke für das Melden - ich konnte das Problem nachvollziehen!

**Comment by col-panic** [comment]
Geführt in https://redmine.medelexis.ch/issues/10717

**Comment by marlovitsh** [comment]
0056 auch...

Am 09.02.2018 09:30 schrieb "Marco Descher" <notifications@github.com>:

**Comment by col-panic** [comment]
Das müsste im aktuellen Master gefixed sein. Kannst du das evtl. testen?

**Comment by marlovitsh** [comment]
Funktioniert alles.
Great!

**Comment by col-panic** [comment]
Übernommen in 3.4 https://github.com/elexis/elexis-3-base/commit/9f18c22c950ac31eea062a2d5361c2b59cc550ce
