### ISSUE TITLE
Tarmed Positionen für einseitige Eingriffe mit verlangter Seitenangabe können falsch doppelt verrechnet werden 

### ISSUE THREAD

**Issue by marlovitsh** [elexis/elexis-3-base#138]
## Problem
Die folgenden Positionen für einseitige Eingriffe können falsch zweifach pro Konsultation addiert werden. Dabei wird nicht einmal die Position hochgezählt auf zwei, sondern sogar als separate Position ein zweites Mal angefügt. Versucht man dann ein drittes Mal zu addieren, kommt erst die Fehlermeldung.

- 20.0290 Operative Versorgung einer Inguinalhernie beim Mädchen ab 7 bis 16 Jahre, einseitig
- 20.0330 Operative Versorgung einer Inguinalhernie beim Erwachsenen älter als 16 Jahre, tension-free, einseitig
- 20.0350 Operative Versorgung einer Inguinalhernie beim Erwachsenen älter als 16 Jahre, jede Methode, exkl. tension-free, einseitig
- 20.0460 Operative Versorgung einer Femoralhernie beim Erwachsenen älter als 16 Jahre, Inguinalisation tension-free, einseitig

## Grund
Alle diese Positionen haben im Tarmed den Vermerk "Für diese Leistung muss angegeben werden, auf welcher Seite sie erbracht worden ist. " (Die Logik für diese Bedingung  ist medizinisch und logisch nicht nachvollziehbar - sie ist kunterbunt irgendwie verteilt - "Exclusive Tension free" ist zBsp nicht dabei)

In TarmedOptifier.add() wird getestet, ob die Position schon vorhanden ist und dann nur hochgezählt - AUSSER, wenn die Seite angegeben werden muss - deshalb wird dann falsch die Position nochmals separat angefügt.
Der entsprechende Stelle im Code ist zu finden nach Comment "Ist der Hinzuzufügende Code vielleicht schon in der Liste? Dann nur Zahl erhöhen.", if (!tc.requiresSide()) {
Wird der Test auskommentiert, läuft alles sauber.

## Folge
Falsche Abrechnungen sind möglich
Es gibt sicher noch mehr dieser Positionen, die falsch mehrfach verrechnet werden können - alle mit Seitenangaben könnten hier betroffen sein.

**Comment by huthomas** [comment]
Die Anzahl wurde immer nur mit dem neuen Verrechnet geprüft. Wenn da noch ein zweites (für die andere Seite) bereits vorhanden war, wurde dessen Anzahl bei der Prüfung ignoriert.

Es werden nun alle Leistungen der Kons der selben Klasse und Code aufsummiert.

Danke fürs Testen!

**Comment by marlovitsh** [comment]
Getestet - funktioniert.

Great.
