### ISSUE TITLE
Agenda löscht Termine beim neu einstellen

### ISSUE THREAD

**Issue by rgwch** [elexis/elexis-3-base#30]
Wenn man über Einstellungen->Agenda->Tageseinteilung->Werte editieren für...
die Tagesgrenzen ändert, dann werden sämtliche Termine ab dem angegebenen Datum gelöscht.

Diese Verhalten ist falsch. Es sollten nur die Tagesgrenzen geändert werden (oder sonst sollte eine deutliche Warnung erfolgen)

**Comment by huthomas** [comment]
Wir hatten das Problem angesehen (Medelexis Redmine Ticket 4498).
Im Ticket sind auch die links auf die Anpassungen in master und 3.1 branch. Das Verhalten sollte dort nun folgedermassen sein. 

- Jetzt werden beim Anpassen der Sperrzeiten, alle bestehenden Sperrzeiten gelöscht, ausser es gibt eine Kollision und auf dem Dialog wurde das beibehalten bestätigt.
- Die neuen Sperrzeiten werden eingefügt, wenn der Tag in einem der Agenda Views geöffnet wird.
- Es werden nun nie bestehende Termine welche keine Sperrzeiten sind gelöscht.

**Comment by ngiger** [comment]
Gemäss unseren Tests ist dieses Problem jetzt gelöst
